---
- hosts: remote
  tasks:
    - name: Create directory
      file:
        path: /tmp/go-echo-service
        state: directory
    - name: Copy built application to the remote server
      copy:
        src: ../.build/app
        dest: /tmp/go-echo-service/app
        mode: 0755
    - name: Create systemd unit file
      template:
        src: go-echo.service.j2
        dest: "/lib/systemd/system/go-echo@.service"
        mode: 644
      become: true
      notify:
        - reload systemctl
    - name: Restart service
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: go-echo@{{ item }}
      with_items:
        - 8000
        - 8001
        - 8002
      become: true
  handlers:
    - name: reload systemctl
      become: true
      command: systemctl daemon-reload
