---
- hosts: remote
  tasks:
    - name: Copy built application to the remote server
      copy:
        src: ../.build/echo-service
        dest: /tmp/echo-service
        mode: 0755
    - name: Create systemd unit file
      template:
        src: echo.service
        dest: "/lib/systemd/system/echo-service@.service"
        mode: 644
      become: true
      notify:
        - reload systemctl
    - name: Restart service
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: echo-service@{{ item }}
      with_items:
        - 8000
        - 8001
        - 8002
      become: true
  handlers:
    - name: reload systemctl
      become: true
      command: systemctl daemon-reload
